import Head from "next/head";

import { OrganizationsPage } from "../../components";

const Organizations = () => {
  return (
    <div>
      <Head>
        <title>Events | Event Bus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <OrganizationsPage />
      </main>
    </div>
  );
};

export default Organizations;
