import Head from "next/head";

import Navigation from "../../common/Navbar/Navigation";
import NewOrganization from "../../components/Organizations/components/NewOrganization";

const CreateOrganization = () => {
  return (
    <div>
      <Head>
        <title>Create Organization | Event Bus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NewOrganization />
      </main>
    </div>
  );
};

export default CreateOrganization;
