import Head from "next/head";
import EventsPage from "../components/events/EventsPage";

const Events = () => {
  return (
    <div>
      <Head>
        <title>Events | Event Bus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <EventsPage />
      </main>
    </div>
  );
};

export default Events;
