import { Container, Row, Text } from "@nextui-org/react";
import Head from "next/head";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Event Bus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container fluid>
          <Row
            fluid
            justify="center"
            align="center"
            css={{
              flexDirection: "column",
              padding: "4rem",
            }}
          >
            <Text h1>Event Bus</Text>

            <Text p>
              EventBus is an Event Management system developed by Google
              Developer Student Clubs - LPU, that helps to create and manage
              events.
            </Text>
          </Row>
        </Container>
      </main>
    </div>
  );
};

export default Home;
