import {
  Button,
  Col,
  Container,
  Input,
  Link,
  Loading,
  Row,
  Spacer,
  Text,
} from "@nextui-org/react";
import Head from "next/head";
import * as NextLink from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useDispatch } from "react-redux";
import { toast } from "react-toastify";
import { register } from "../redux/actionCreators/auth.actionCreator";

const Register = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [success, setSuccess] = useState(false);
  const [registering, setRegistering] = useState(false);

  const dispatch = useDispatch();
  const router = useRouter();

  const handleSubmit = (e) => {
    e.preventDefault();

    if (!email || !password || !firstName || !lastName) {
      return toast.error("Please fill in all fields!!");
    }

    const payload = {
      email,
      password,
      name: {
        first: firstName,
        last: lastName,
      },
    };

    setRegistering(true);

    dispatch(register(payload, setSuccess, setRegistering));
  };

  useEffect(() => {
    if (success) {
      setEmail("");
      setPassword("");
      setFirstName("");
      setLastName("");

      router.push("/login");
    }
  }, [success, router]);

  return (
    <Container
      xs
      display="flex"
      direction="column"
      alignItems="center"
      justify="center"
    >
      <Head>
        <title>Sign Up | Event Bus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text size={"3.5rem"} h1>
        Sign Up
      </Text>
      <form
        onSubmit={handleSubmit}
        style={{
          width: "80%",
          padding: "3rem",
          borderRadius: "0.5rem",
        }}
      >
        <Row>
          <Col span={6}>
            <Input
              width="100%"
              bordered
              required
              clearable
              labelPlaceholder="First Name"
              value={firstName}
              onChange={(e) => setFirstName(e.target.value)}
            />
          </Col>
          <Spacer x={0.5} />
          <Col span={6}>
            <Input
              width="100%"
              bordered
              required
              clearable
              labelPlaceholder="Last Name"
              value={lastName}
              onChange={(e) => setLastName(e.target.value)}
            />
          </Col>
        </Row>
        <Spacer y={1.5} />
        <Input
          width="100%"
          type={"email"}
          bordered
          required
          clearable
          labelPlaceholder="Email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        />
        <Spacer y={1.5} />
        <Input
          width="100%"
          type={"password"}
          bordered
          required
          clearable
          labelPlaceholder="Password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
        <Spacer y={2} />
        <Button
          css={{
            width: "100%",
          }}
          type="submit"
        >
          {registering ? (
            <Loading color="currentColor" size="sm" />
          ) : (
            "Register"
          )}
        </Button>
      </form>
      <Spacer y={1.5} />
      <Row justify="center">
        <Text>Already have an account?</Text>
        <Spacer x={0.5} />
        <Link as={NextLink} href="/login">
          <a>
            <Text color="primary">Login</Text>
          </a>
        </Link>
      </Row>
    </Container>
  );
};

export default Register;
